name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore wdc3.net
    - name: Build
      run: dotnet build wdc3.net --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
